name: Build Exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Check versions
      run: |
        node -v
        npm -v
        python -V

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Build exe for pars.py
      run: pyinstaller --onefile pars.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for json_składnia.py
      run: pyinstaller --onefile json_składnia.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for json_zgodność.py
      run: pyinstaller --onefile json_zgodność.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for yaml_weryfikacja.py
      run: pyinstaller --onefile yaml_weryfikacja.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for yaml_zgodność.py
      run: pyinstaller --onefile yaml_zgodność.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for xml_weryfikacja.py
      run: pyinstaller --onefile xml_weryfikacja.py
      working-directory: ${{ github.workspace }}

    - name: Build exe for xml_zgodność.py
      run: pyinstaller --onefile xml_zgodność.py
      working-directory: ${{ github.workspace }}

    - name: Upload exe files
      uses: actions/upload-artifact@v4
      with:
        name: exe-files
        path: |
          dist/pars
          dist/json_składnia
          dist/json_zgodność
          dist/yaml_weryfikacja
          dist/yaml_zgodność
          dist/xml_weryfikacja
          dist/xml_zgodność
